import { defineContract } from 'stitchkit';
import { AttachmentReferenceSchema } from '../attachments/reference.ts';
import {
  AttachmentBeginSchema,
  AttachmentCancelReceiptSchema,
  AttachmentChunkSchema,
  AttachmentReadReceiptSchema,
  AttachmentReadSchema,
  AttachmentUploadReceiptSchema,
  AttachmentUploadSelectorSchema,
} from '../attachments/schema.ts';
import {
  MessageOperationReadSchema,
  MessageOperationResultSchema,
} from '../chat/messageOperationSchema.ts';
import { NativeForkRequestSchema } from '../context/schema.ts';
import {
  ExternalContentCapabilitiesSchema,
  ExternalContentReadSchema,
  ExternalContentResultSchema,
  ExternalContentSelectorSchema,
} from '../external/contentSchema.ts';
import { EXTERNAL_MAX_BYTES, ExternalStatusSnapshotSchema } from '../external/resident-schema.ts';
import { RuntimeCatalogInputSchema, RuntimeCatalogSchema } from '../runtime/capabilities.ts';
import {
  SteeringInputSchema,
  SteeringReadResultSchema,
  SteeringReceiptSchema,
  SteeringSelectorSchema,
} from '../steering/schema.ts';
import {
  ControlCompactSchema,
  ControlContextOperationReadSchema,
  ControlContextOperationResultSchema,
  ControlHistoryReadSchema,
  ControlHistoryResultSchema,
} from './contextSchema.ts';
import { ControlDirectoryReadSchema, ControlDirectoryResultSchema } from './directorySchema.ts';
import {
  CONTROL_MAX_BYTES,
  ControlActionReceiptSchema,
  ControlArchiveReceiptSchema,
  ControlCommandCatalogSchema,
  ControlCommandsReadSchema,
  ControlCreateReceiptSchema,
  ControlCreateSchema,
  ControlInterruptSchema,
  ControlMcpControlReceiptSchema,
  ControlMcpControlSchema,
  ControlMcpListSchema,
  ControlMcpReadSchema,
  ControlMessageReceiptSchema,
  ControlMessageSchema,
  ControlModelCatalogSchema,
  ControlModelsReadSchema,
  ControlNativeReadSchema,
  ControlNativeResponseReceiptSchema,
  ControlNativeResponseSchema,
  ControlNativeSnapshotSchema,
  ControlPermissionModeReceiptSchema,
  ControlPermissionModeSchema,
  ControlRewindReceiptSchema,
  ControlRewindSchema,
  ControlRowSchema,
  ControlRunCommandReceiptSchema,
  ControlRunCommandSchema,
  ControlSnapshotSchema,
  ControlTargetSchema,
  ControlTranscriptReadSchema,
  ControlTranscriptResultSchema,
  ControlWaitResultSchema,
  ControlWaitSchema,
} from './schema.ts';
import {
  SelectionReadSchema,
  SelectionResultSchema,
  SelectionUpdateSchema,
} from './selectionSchema.ts';

export const controlContract = defineContract(
  { prefix: 'control', scope: 'local' },
  {
    externalHistory: {
      method: 'POST',
      path: '/external/history',
      desc: 'Read bounded external authored text without writer mutation',
      input: ExternalContentReadSchema,
      output: ExternalContentResultSchema,
      idempotent: true,
      timeout: 7_000,
    },
    externalCapabilities: {
      method: 'POST',
      path: '/external/capabilities',
      desc: 'Read exact external content and control eligibility',
      input: ExternalContentSelectorSchema,
      output: ExternalContentCapabilitiesSchema,
      idempotent: true,
      timeout: 7_000,
    },
    messageOperation: {
      method: 'POST',
      path: '/message/operation',
      desc: 'Read retained exact message-to-native-turn evidence without resubmission',
      input: MessageOperationReadSchema,
      output: MessageOperationResultSchema,
      idempotent: true,
    },
    transcript: {
      method: 'POST',
      path: '/transcript',
      desc: 'Read a bounded transcript window with the cursor a caller pages by',
      input: ControlTranscriptReadSchema,
      output: ControlTranscriptResultSchema,
      idempotent: true,
      timeout: 7_000,
    },
    history: {
      method: 'POST',
      path: '/history',
      desc: 'Read a bounded native history page through its existing owner',
      input: ControlHistoryReadSchema,
      output: ControlHistoryResultSchema,
      idempotent: true,
      timeout: 7_000,
    },
    compact: {
      method: 'POST',
      path: '/context/compact',
      desc: 'Accept an exact idle native compaction operation',
      input: ControlCompactSchema,
      output: ControlContextOperationResultSchema,
      idempotent: true,
    },
    contextOperation: {
      method: 'POST',
      path: '/context/operation',
      desc: 'Read durable native compaction completion evidence',
      input: ControlContextOperationReadSchema,
      output: ControlContextOperationResultSchema,
      idempotent: true,
    },
    fork: {
      method: 'POST',
      path: '/fork',
      desc: 'Fork one idle native conversation without changing its source',
      input: NativeForkRequestSchema,
      output: ControlCreateReceiptSchema,
      idempotent: true,
      timeout: 65_000,
    },
    steer: {
      method: 'POST',
      path: '/turn/steer',
      desc: 'Submit content to an exact active native turn',
      input: SteeringInputSchema,
      output: SteeringReceiptSchema,
      idempotent: true,
      timeout: 15_000,
    },
    steeringOperation: {
      method: 'POST',
      path: '/turn/steering-operation',
      desc: 'Read exact steering acceptance without resubmission',
      input: SteeringSelectorSchema,
      output: SteeringReadResultSchema,
      idempotent: true,
    },
    selection: {
      method: 'POST',
      path: '/selection',
      desc: "Read the exact session's revisioned native turn defaults",
      input: SelectionReadSchema,
      output: SelectionResultSchema,
      idempotent: true,
    },
    select: {
      method: 'POST',
      path: '/selection/update',
      desc: 'Change native turn defaults between turns with revision CAS',
      input: SelectionUpdateSchema,
      output: SelectionResultSchema,
      idempotent: true,
    },
    attachmentBegin: {
      method: 'POST',
      path: '/attachment/begin',
      desc: 'Reserve one bounded image upload for an exact target',
      input: AttachmentBeginSchema,
      output: AttachmentUploadReceiptSchema,
      idempotent: true,
    },
    attachmentChunk: {
      method: 'POST',
      path: '/attachment/chunk',
      desc: 'Append one authenticated bounded image chunk',
      input: AttachmentChunkSchema,
      output: AttachmentUploadReceiptSchema,
      idempotent: true,
    },
    attachmentFinalize: {
      method: 'POST',
      path: '/attachment/finalize',
      desc: 'Verify complete image bytes and return an immutable reference',
      input: AttachmentUploadSelectorSchema,
      output: AttachmentReferenceSchema,
      idempotent: true,
    },
    attachmentCancel: {
      method: 'POST',
      path: '/attachment/cancel',
      desc: 'Cancel an unretained image upload',
      input: AttachmentUploadSelectorSchema,
      output: AttachmentCancelReceiptSchema,
      idempotent: true,
    },
    attachmentRead: {
      method: 'POST',
      path: '/attachment/read',
      desc: 'Read one authorized preview chunk; never expose owner paths',
      input: AttachmentReadSchema,
      output: AttachmentReadReceiptSchema,
      idempotent: true,
    },
    runtimes: {
      method: 'POST',
      path: '/runtimes',
      desc: 'Discover configured execution runtimes and explicit capabilities',
      toolName: 'runtimes',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: RuntimeCatalogInputSchema,
      output: RuntimeCatalogSchema,
    },
    directories: {
      method: 'POST',
      path: '/directories',
      desc: 'List directory names without following symlinks',
      toolName: 'directories',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlDirectoryReadSchema,
      output: ControlDirectoryResultSchema,
    },
    list: {
      method: 'GET',
      path: '/sessions',
      desc: 'Read the prepared managed-session snapshot',
      toolName: 'sessions',
      expose: ['HTTP', 'CLI', 'MCP'],
      output: ControlSnapshotSchema,
    },
    external: {
      method: 'GET',
      path: '/external',
      desc: 'Read prepared external native thread states; does not adopt or start threads',
      toolName: 'external',
      expose: ['HTTP', 'CLI', 'MCP'],
      output: ExternalStatusSnapshotSchema,
    },
    get: {
      method: 'POST',
      path: '/session',
      desc: 'Read one exact managed session',
      toolName: 'session',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlTargetSchema,
      output: ControlRowSchema,
    },
    create: {
      method: 'POST',
      path: '/create',
      desc: 'Idempotently create one workspace-scoped managed runtime session',
      toolName: 'create_session',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlCreateSchema,
      output: ControlCreateReceiptSchema,
      timeout: 65_000,
    },
    archive: {
      method: 'POST',
      path: '/archive',
      desc: 'Archive and stop one exact managed identity without deleting provider history',
      toolName: 'archive_session',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlTargetSchema,
      output: ControlArchiveReceiptSchema,
    },
    message: {
      method: 'POST',
      path: '/message',
      desc: 'Accept an identity-pinned message into durable chat; acceptance is not completion',
      toolName: 'message',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlMessageSchema,
      output: ControlMessageReceiptSchema,
    },
    start: {
      method: 'POST',
      path: '/start',
      desc: 'Start an existing registered session without changing its identity',
      toolName: 'start',
      expose: ['HTTP', 'CLI', 'MCP'],
      input: ControlTargetSchema,
      output: ControlActionReceiptSchema,
    },
    interrupt: {
      method: 'POST',
      path: '/interrupt',
      desc: 'Interrupt the exact active native turn; never answer an approval or input request',
      toolName: 'interrupt',
      expose: ['HTTP', 'CLI', 'MCP'],
      input: ControlInterruptSchema,
      output: ControlActionReceiptSchema,
    },
    native: {
      method: 'POST',
      path: '/native',
      desc: 'Read a bounded native item snapshot after an optional cursor',
      toolName: 'native_items',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlNativeReadSchema,
      output: ControlNativeSnapshotSchema,
    },
    models: {
      method: 'POST',
      path: '/models',
      desc: 'Read the connected App Server model catalog after an optional cursor; provider-owned and read-only',
      toolName: 'models',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      timeout: 10_000,
      input: ControlModelsReadSchema,
      output: ControlModelCatalogSchema,
    },
    commands: {
      method: 'POST',
      path: '/commands',
      desc: 'Read the slash commands this session runtime offers',
      toolName: 'commands',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlCommandsReadSchema,
      output: ControlCommandCatalogSchema,
    },
    command: {
      method: 'POST',
      path: '/command',
      desc: 'Run one slash command the runtime offers, as a turn of its own',
      toolName: 'run_command',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlRunCommandSchema,
      output: ControlRunCommandReceiptSchema,
    },
    permissionMode: {
      method: 'POST',
      path: '/permission-mode',
      desc: 'Set the permission mode the session runs its next turns under',
      toolName: 'permission_mode',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlPermissionModeSchema,
      output: ControlPermissionModeReceiptSchema,
    },
    mcpServers: {
      method: 'POST',
      path: '/mcp',
      desc: 'Read the MCP servers of a session and each one connection status',
      toolName: 'mcp_servers',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlMcpReadSchema,
      output: ControlMcpListSchema,
    },
    mcpControl: {
      method: 'POST',
      path: '/mcp/control',
      desc: 'Enable, disable or reconnect one MCP server of a session',
      toolName: 'mcp_control',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      timeout: 30_000,
      input: ControlMcpControlSchema,
      output: ControlMcpControlReceiptSchema,
    },
    rewind: {
      method: 'POST',
      path: '/rewind',
      desc: 'Preview or perform a rewind of the files a session modified',
      toolName: 'rewind_files',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      timeout: 60_000,
      input: ControlRewindSchema,
      output: ControlRewindReceiptSchema,
    },
    respond: {
      method: 'POST',
      path: '/native/respond',
      desc: 'Answer one exact current native approval or input request',
      toolName: 'respond_native',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlNativeResponseSchema,
      output: ControlNativeResponseReceiptSchema,
    },
    wait: {
      method: 'POST',
      path: '/wait',
      desc: 'Wait for a native session between turns, including pending chat pickup',
      toolName: 'wait',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlWaitSchema,
      output: ControlWaitResultSchema,
    },
  },
);

export const controlEventsContract = defineContract(
  { prefix: 'control-events', scope: 'local' },
  {
    watch: {
      method: 'GET',
      path: '/',
      desc: 'Subscribe to bounded absolute snapshots; reconnect establishes a fresh baseline',
      stream: {
        item: ControlSnapshotSchema,
        format: 'ndjson',
        maxFrameBytes: CONTROL_MAX_BYTES + 1024,
        heartbeatMs: 2000,
      },
    },
    watchExternal: {
      method: 'GET',
      path: '/external',
      desc: 'Subscribe to prepared external native status, including unavailable and stale outcomes',
      stream: {
        item: ExternalStatusSnapshotSchema,
        format: 'ndjson',
        maxFrameBytes: EXTERNAL_MAX_BYTES + 1024,
        heartbeatMs: 2000,
      },
    },
    watchNative: {
      method: 'POST',
      path: '/native',
      desc: 'Subscribe to bounded native item frames; reset marks cursor resync',
      input: ControlNativeReadSchema,
      stream: {
        item: ControlNativeSnapshotSchema,
        format: 'ndjson',
        maxFrameBytes: CONTROL_MAX_BYTES + 1024,
        heartbeatMs: 2000,
      },
    },
  },
);
