import { defineContract } from 'stitchkit';
import { AttachmentReferenceSchema } from '../../attachments/reference.ts';
import {
  AttachmentBeginSchema,
  AttachmentCancelReceiptSchema,
  AttachmentChunkSchema,
  AttachmentReadReceiptSchema,
  AttachmentReadSchema,
  AttachmentUploadReceiptSchema,
  AttachmentUploadSelectorSchema,
} from '../../attachments/schema.ts';
import {
  MessageOperationReadSchema,
  MessageOperationResultSchema,
} from '../../chat/messageOperationSchema.ts';
import { NativeForkRequestSchema } from '../../context/schema.ts';
import {
  ExternalContentCapabilitiesSchema,
  ExternalContentReadSchema,
  ExternalContentResultSchema,
  ExternalContentSelectorSchema,
} from '../../external/contentSchema.ts';
import { ExternalStatusSnapshotSchema } from '../../external/residentSchema.ts';
import { RuntimeCatalogInputSchema, RuntimeCatalogSchema } from '../../runtime/capabilities.ts';
import {
  SteeringInputSchema,
  SteeringReadResultSchema,
  SteeringReceiptSchema,
  SteeringSelectorSchema,
} from '../../steering/schema.ts';
import {
  UsageListResultSchema,
  UsageListSchema,
  UsageReadSchema,
  UsageSummarySchema,
} from '../../usage/schema.ts';
import {
  ControlCompactSchema,
  ControlContextOperationReadSchema,
  ControlContextOperationResultSchema,
  ControlHistoryReadSchema,
  ControlHistoryResultSchema,
} from './context.ts';
import { ControlRowSchema, ControlSnapshotSchema, ControlTargetSchema } from './core.ts';
import { ControlDirectoryReadSchema, ControlDirectoryResultSchema } from './directory.ts';
import {
  ControlActionReceiptSchema,
  ControlInterruptSchema,
  ControlMessageCancelReceiptSchema,
  ControlMessageCancelSchema,
  ControlMessageReceiptSchema,
  ControlMessageSchema,
} from './message.ts';
import { ControlModelCatalogSchema, ControlModelsReadSchema } from './model.ts';
import {
  ControlNativeReadSchema,
  ControlNativeResponseReceiptSchema,
  ControlNativeResponseSchema,
  ControlNativeSnapshotSchema,
  ControlTranscriptReadSchema,
  ControlTranscriptResultSchema,
} from './native.ts';
import {
  ControlCommandCatalogSchema,
  ControlCommandsReadSchema,
  ControlMcpControlReceiptSchema,
  ControlMcpControlSchema,
  ControlMcpListSchema,
  ControlMcpReadSchema,
  ControlPermissionModeReceiptSchema,
  ControlPermissionModeSchema,
  ControlPermissionReadSchema,
  ControlPermissionResultSchema,
  ControlPermissionUpdateSchema,
  ControlRewindReceiptSchema,
  ControlRewindSchema,
  ControlRunCommandReceiptSchema,
  ControlRunCommandSchema,
  ControlWaitResultSchema,
  ControlWaitSchema,
} from './runtimeOps.ts';
import { SelectionReadSchema, SelectionResultSchema, SelectionUpdateSchema } from './selection.ts';
import {
  ControlArchiveReceiptSchema,
  ControlCreateReceiptSchema,
  ControlCreateSchema,
} from './session.ts';

export const controlContract = defineContract(
  { prefix: 'control', scope: 'local' },
  {
    'usage.read': {
      method: 'POST',
      path: '/usage',
      desc: 'Read measured usage without conversation content',
      input: UsageReadSchema,
      output: UsageSummarySchema,
      idempotent: true,
      expose: ['HTTP', 'CLI', 'MCP'],
      timeout: 7_000,
      tool: { name: 'usage' },
    },
    'usage.list': {
      method: 'POST',
      path: '/usage/list',
      desc: 'Read a bounded page of local session usage',
      input: UsageListSchema,
      output: UsageListResultSchema,
      idempotent: true,
      expose: ['HTTP', 'CLI', 'MCP'],
      timeout: 7_000,
      tool: { name: 'usage_list' },
    },
    'external.history': {
      method: 'POST',
      path: '/external/history',
      desc: 'Read bounded external authored text without writer mutation',
      input: ExternalContentReadSchema,
      output: ExternalContentResultSchema,
      idempotent: true,
      timeout: 7_000,
    },
    'external.capabilities': {
      method: 'POST',
      path: '/external/capabilities',
      desc: 'Read exact external content and control eligibility',
      input: ExternalContentSelectorSchema,
      output: ExternalContentCapabilitiesSchema,
      idempotent: true,
      timeout: 7_000,
    },
    'message.cancel': {
      method: 'POST',
      path: '/message/cancel',
      desc: 'Withdraw one accepted letter of the caller that has not been delivered',
      input: ControlMessageCancelSchema,
      output: ControlMessageCancelReceiptSchema,
      idempotent: true,
    },
    'message.operation': {
      method: 'POST',
      path: '/message/operation',
      desc: 'Read retained exact message-to-native-turn evidence without resubmission',
      input: MessageOperationReadSchema,
      output: MessageOperationResultSchema,
      idempotent: true,
    },
    'transcript.read': {
      method: 'POST',
      path: '/transcript',
      desc: 'Read a bounded transcript window with the cursor a caller pages by',
      input: ControlTranscriptReadSchema,
      output: ControlTranscriptResultSchema,
      idempotent: true,
      timeout: 7_000,
    },
    'history.read': {
      method: 'POST',
      path: '/history',
      desc: 'Read a bounded native history page through its existing owner',
      input: ControlHistoryReadSchema,
      output: ControlHistoryResultSchema,
      idempotent: true,
      timeout: 7_000,
    },
    'context.compact': {
      method: 'POST',
      path: '/context/compact',
      desc: 'Accept an exact idle native compaction operation',
      input: ControlCompactSchema,
      output: ControlContextOperationResultSchema,
      idempotent: true,
    },
    'context.operation': {
      method: 'POST',
      path: '/context/operation',
      desc: 'Read durable native compaction completion evidence',
      input: ControlContextOperationReadSchema,
      output: ControlContextOperationResultSchema,
      idempotent: true,
    },
    'session.fork': {
      method: 'POST',
      path: '/fork',
      desc: 'Fork one idle native conversation without changing its source',
      input: NativeForkRequestSchema,
      output: ControlCreateReceiptSchema,
      idempotent: true,
      timeout: 30_000,
    },
    'turn.steer': {
      method: 'POST',
      path: '/turn/steer',
      desc: 'Submit content to an exact active native turn',
      input: SteeringInputSchema,
      output: SteeringReceiptSchema,
      idempotent: true,
      timeout: 15_000,
    },
    'turn.steering-operation': {
      method: 'POST',
      path: '/turn/steering-operation',
      desc: 'Read exact steering acceptance without resubmission',
      input: SteeringSelectorSchema,
      output: SteeringReadResultSchema,
      idempotent: true,
    },
    'selection.read': {
      method: 'POST',
      path: '/selection',
      desc: "Read the exact session's revisioned native turn defaults",
      input: SelectionReadSchema,
      output: SelectionResultSchema,
      idempotent: true,
    },
    'selection.update': {
      method: 'POST',
      path: '/selection/update',
      desc: 'Change native turn defaults between turns with revision CAS',
      input: SelectionUpdateSchema,
      output: SelectionResultSchema,
      idempotent: true,
    },
    'attachment.begin': {
      method: 'POST',
      path: '/attachment/begin',
      desc: 'Reserve one bounded image upload for an exact target',
      input: AttachmentBeginSchema,
      output: AttachmentUploadReceiptSchema,
      idempotent: true,
    },
    'attachment.chunk': {
      method: 'POST',
      path: '/attachment/chunk',
      desc: 'Append one authenticated bounded image chunk',
      input: AttachmentChunkSchema,
      output: AttachmentUploadReceiptSchema,
      idempotent: true,
    },
    'attachment.finalize': {
      method: 'POST',
      path: '/attachment/finalize',
      desc: 'Verify complete image bytes and return an immutable reference',
      input: AttachmentUploadSelectorSchema,
      output: AttachmentReferenceSchema,
      idempotent: true,
    },
    'attachment.cancel': {
      method: 'POST',
      path: '/attachment/cancel',
      desc: 'Cancel an unretained image upload',
      input: AttachmentUploadSelectorSchema,
      output: AttachmentCancelReceiptSchema,
      idempotent: true,
    },
    'attachment.read': {
      method: 'POST',
      path: '/attachment/read',
      desc: 'Read one authorized preview chunk; never expose owner paths',
      input: AttachmentReadSchema,
      output: AttachmentReadReceiptSchema,
      idempotent: true,
    },
    'runtime.list': {
      method: 'POST',
      path: '/runtimes',
      desc: 'Discover configured execution runtimes and explicit capabilities',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: RuntimeCatalogInputSchema,
      output: RuntimeCatalogSchema,
      tool: { name: 'runtimes' },
    },
    'directory.list': {
      method: 'POST',
      path: '/directories',
      desc: 'List directory names without following symlinks',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlDirectoryReadSchema,
      output: ControlDirectoryResultSchema,
      tool: { name: 'directories' },
    },
    'session.list': {
      method: 'POST',
      path: '/sessions',
      desc: 'Read the prepared managed-session snapshot',
      expose: ['HTTP', 'CLI', 'MCP'],
      output: ControlSnapshotSchema,
      tool: { name: 'sessions' },
    },
    'external.list': {
      method: 'POST',
      path: '/external',
      desc: 'Read prepared external native thread states; does not adopt or start threads',
      expose: ['HTTP', 'CLI', 'MCP'],
      output: ExternalStatusSnapshotSchema,
      tool: { name: 'external' },
    },
    'session.get': {
      method: 'POST',
      path: '/session',
      desc: 'Read one exact managed session',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlTargetSchema,
      output: ControlRowSchema,
      tool: { name: 'session' },
    },
    'session.create': {
      method: 'POST',
      path: '/create',
      desc: 'Idempotently create one workspace-scoped managed runtime session',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlCreateSchema,
      output: ControlCreateReceiptSchema,
      timeout: 30_000,
      tool: { name: 'create_session' },
    },
    'session.archive': {
      method: 'POST',
      path: '/archive',
      desc: 'Archive and stop one exact managed identity without deleting provider history',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlTargetSchema,
      output: ControlArchiveReceiptSchema,
      tool: { name: 'archive_session' },
    },
    'message.send': {
      method: 'POST',
      path: '/message',
      desc: 'Accept an identity-pinned message into durable chat; acceptance is not completion',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlMessageSchema,
      output: ControlMessageReceiptSchema,
      tool: { name: 'message' },
    },
    'session.start': {
      method: 'POST',
      path: '/start',
      desc: 'Start an existing registered session without changing its identity',
      expose: ['HTTP', 'CLI', 'MCP'],
      input: ControlTargetSchema,
      output: ControlActionReceiptSchema,
      tool: { name: 'start' },
    },
    'turn.interrupt': {
      method: 'POST',
      path: '/interrupt',
      desc: 'Interrupt the exact active native turn; never answer an approval or input request',
      expose: ['HTTP', 'CLI', 'MCP'],
      input: ControlInterruptSchema,
      output: ControlActionReceiptSchema,
      tool: { name: 'interrupt' },
    },
    'native.read': {
      method: 'POST',
      path: '/native',
      desc: 'Read a bounded native item snapshot after an optional cursor',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlNativeReadSchema,
      output: ControlNativeSnapshotSchema,
      tool: { name: 'native_items' },
    },
    'model.list': {
      method: 'POST',
      path: '/models',
      desc: 'Read the connected App Server model catalog after an optional cursor; provider-owned and read-only',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      timeout: 10_000,
      input: ControlModelsReadSchema,
      output: ControlModelCatalogSchema,
      tool: { name: 'models' },
    },
    'command.list': {
      method: 'POST',
      path: '/commands',
      desc: 'Read the slash commands this session runtime offers',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlCommandsReadSchema,
      output: ControlCommandCatalogSchema,
      tool: { name: 'commands' },
    },
    'command.run': {
      method: 'POST',
      path: '/command',
      desc: 'Run one slash command the runtime offers, as a turn of its own',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlRunCommandSchema,
      output: ControlRunCommandReceiptSchema,
      tool: { name: 'run_command' },
    },
    'permission.mode': {
      method: 'POST',
      path: '/permission-mode',
      desc: 'Set the permission mode the session runs its next turns under',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlPermissionModeSchema,
      output: ControlPermissionModeReceiptSchema,
      tool: { name: 'permission_mode' },
    },
    'permission.read': {
      method: 'POST',
      path: '/permission',
      desc: 'Read the permission mode accepted for future turns and the one observed natively',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlPermissionReadSchema,
      output: ControlPermissionResultSchema,
      tool: { name: 'permission_read' },
    },
    'permission.update': {
      method: 'POST',
      path: '/permission/update',
      desc: 'Replace the accepted permission mode, refusing a stale expected revision',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlPermissionUpdateSchema,
      output: ControlPermissionResultSchema,
      tool: { name: 'permission_update' },
    },
    'mcp.list': {
      method: 'POST',
      path: '/mcp',
      desc: 'Read the MCP servers of a session and each one connection status',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlMcpReadSchema,
      output: ControlMcpListSchema,
      tool: { name: 'mcp_servers' },
    },
    'mcp.control': {
      method: 'POST',
      path: '/mcp/control',
      desc: 'Enable, disable or reconnect one MCP server of a session',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      timeout: 30_000,
      input: ControlMcpControlSchema,
      output: ControlMcpControlReceiptSchema,
      tool: { name: 'mcp_control' },
    },
    'session.rewind': {
      method: 'POST',
      path: '/rewind',
      desc: 'Preview or perform a rewind of the files a session modified',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      timeout: 30_000,
      input: ControlRewindSchema,
      output: ControlRewindReceiptSchema,
      tool: { name: 'rewind_files' },
    },
    'native.respond': {
      method: 'POST',
      path: '/native/respond',
      desc: 'Answer one exact current native approval or input request',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlNativeResponseSchema,
      output: ControlNativeResponseReceiptSchema,
      tool: { name: 'respond_native' },
    },
    'session.wait': {
      method: 'POST',
      path: '/wait',
      desc: 'Wait for a native session between turns, including pending chat pickup',
      expose: ['HTTP', 'CLI', 'MCP'],
      idempotent: true,
      input: ControlWaitSchema,
      output: ControlWaitResultSchema,
      tool: { name: 'wait' },
    },
  },
);
